# Generated by Django 2.0.6 on 2018-10-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=255)),
                ('ano', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=50, verbose_name='Nome')),
                ('etiqueta', models.TextField(max_length=50, verbose_name='Etiqueta')),
                ('carga_horario', models.IntegerField(verbose_name='Carga Horaria')),
            ],
        ),
    ]
